### NUMPY
- Numerical python
- we use numpy only for arrays

In [ ]:
import numpy as np

In [ ]:
l=[100,200,300,400,500]
[x+50 for x in l]

[150, 250, 350, 450, 550]

Arrays works faster than the lists,so numpy uses array

In [ ]:
l=[10,20,30,40,50]
type(l)
a1=np.array(l)
a1

array([10, 20, 30, 40, 50])

In [ ]:
l1=[10,2,3.5,7,'np','6j+c']
a2=np.array(l1)
type(a2)
print(a2)

['10' '2' '3.5' '7' 'np' '6j+c']


Arrays accepts only homogeneous data

In [ ]:
#when we try to add 2 lists it will concatenate the elements from l1 to l2
l1=[10,20,30,40,50]
l2=[1,2,3,4,5]
print(l1+l2)

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]


In [ ]:
#when we try to add array elements,it will sum up the elements present in same index value
arr1=np.array(l1)
arr2=np.array(l2)
print(arr1+arr2)

[11 22 33 44 55]


In [ ]:
arr3=np.array([10,2,5,60,40,80,8,4])
arr3

array([10,  2,  5, 60, 40, 80,  8,  4])

In [ ]:
'''
arr2+arr3

ValueError: operands could not be broadcast together with shapes (5,) (8,) 
***elements present in both array should be same size*** 
'''

'\narr2+arr3\n\nValueError: operands could not be broadcast together with shapes (5,) (8,) \nelements present in both array should be same size\n'

In [ ]:
arr4=np.array([[10,20],[30,40],[50,60]])
arr4

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
arr4.ndim  # gives dimension of array

2

In [ ]:
arr4.shape  #gives no of columns and rows

(3, 2)

In [ ]:
arr4.size  # gives no of elements present in the array 

6

In [ ]:
arr4.itemsize #gives size of each item(in bytes)

8

In [ ]:
arr4.nbytes #gives sum of size of items-->(6(elements)*8(size of each item))

48