In [1]:
import numpy as np

In [2]:
r=range(0,100,2)
a=np.array(r)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [3]:
#instead of range function we use arange function in numpy
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### linspace-->divides the numbers into 50(default) parts equally

linspace(start,step,num,,endpoints)
- `num`=number how many parts we have to divide
- `retstep`=return step values

In [4]:
np.linspace(0,10)
np.linspace(0,10,num=5) #array([ 0. ,  2.5,  5. ,  7.5, 10. ])
np.linspace(0,10,num=5,retstep=True) #(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), np.float64(2.5))
np.linspace(0,10,num=5,retstep=True,endpoint=False) #(array([0., 2., 4., 6., 8.]), np.float64(2.0))

(array([0., 2., 4., 6., 8.]), np.float64(2.0))

## Array Creation Methods

### Zero function

- It creates matrix containing only zero
- syntax: np.zeroes(shape,dtype=float,order='C')
- return type: ndarray

In [5]:
np.zeros(2)
np .zeros((2,3))
np.zeros((2,3,4,)) #2-blocks,3-rows,4-columns

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Ones function

- It creates matrix containing only one
- syntax: np.zeroes(shape,dtype=float,order='C')

In [6]:
np.ones(2)  #array([1., 1.])
np.ones((2,3)) ##2-rows,3-columns
np.ones((2,3,5)) #2-blocks,3-rows,5-columns

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### Eye function

- generates square matrix in which diagonal contains 1 rest all will be zero(0).

In [7]:
np.eye(3)
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Full function
- fill the matrix with the same element which we have given
- syntax: np.full(size,element)

In [8]:
np.full(2,5) #array([5, 5])
np.full((2,4),100) #2-rows,4-columns,element-100

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

### Random Module
- used to generate random numbers

In [9]:
import numpy.random as rd


In [10]:
#gives numbers between 0 to 2 , 2 is excluded
rd.randint(2)

0

In [11]:
rd.randint(10,100) #generates numbers between 10 to 100
rd.randint(10,100,(3)) #generates matrix of 3 columns
rd.randint(10,100,(3,2)) #generates matrix with random numbers of 3-rows and 2-columns

array([[15, 31],
       [41, 10],
       [76, 81]], dtype=int32)

### Seed method
- seed value used to fix the values instead of generating random numbers everytime we execute

In [12]:
rd.seed(2)
rd.randint(10,100,(3,2))

print(rd.randint(10,100,(3,2)))

[[85 17]
 [44 59]
 [85 95]]


### rand() method
- generates random numbers between 0-1 (float values)
- generates only positive values
- syntax: rd.rand(size)

In [13]:
rd.rand(3)
rd.rand(2,3) #2-rows, 3-columns

array([[0.81822672, 0.68302599, 0.49856117],
       [0.58679698, 0.71975423, 0.25849809]])

### randn() method
- generates random numbers between 0-1 (float values)
- generates both positive and negative values
- generated random numbers mean=0, standard deviation=1
- syntax: rd.randn(size)

In [14]:
r=rd.randn(2)
print(r)

print(np.mean(r))
print(np.std(r))

[-2.24587483  1.11957525]
-0.5631497905172993
1.6827250392436395


In [15]:
r1=rd.randn(2,3)
print(r1)

print(np.mean(r1))
print(np.std(r1))

[[-1.054368   -1.0088915  -0.06752199]
 [-0.08142505  2.83521598 -0.24617517]]
0.06280571090271514
1.3048708580404422


### choice() method
-used to choose the elements which we want

In [16]:
l=[10,20,30,40,50]
rd.choice(l) #np.int64(40)
rd.choice(l,3,replace=False) # array([40, 30, 50])   #replace-->used to avoid duplicate elements
rd.choice(l,(2,3))

array([[10, 30, 30],
       [20, 10, 20]])

In [17]:
l1=['purple','red','yellow','maroon','pink','green','blue','white']
rd.choice(l1) #np.str_('yellow')
rd.choice(l1,3,replace=False) #array(['maroon', 'purple', 'white'], dtype='<U6')
rd.choice(l1,3,replace=False,p=[0.17,0.1,0.12,0,0,0.11,0.5,0]) #sum of the values should be equal to=1

array(['blue', 'red', 'green'], dtype='<U6')