In [1]:
import numpy as np

In [11]:
lst1=[10,20,30,40,50]
lst1[1] #20
arr1=np.array(lst1)
arr1

array([10, 20, 30, 40, 50])

In [12]:
lst2=[[10,20,30,40],[50,60,70,80],[90,18,21,11]]
lst2[1][1] #60
# '''
# lst2[1,1] 
# TypeError: list indices must be integers or slices, not tuple
# '''

arr2=np.array(lst2)
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 18, 21, 11]])

In [17]:
# array supports multi-indexing
print(arr1[2]) 
print(arr2[1,1]) 
print(arr2[1][1]) 
print(arr2[1][3])

30
60
60
80


### Slicing()

In [ ]:
#using list
print(lst1[::-1])

[50, 40, 30, 20, 10]


In [21]:
print(lst2[::-1])
print(lst2[::-1][2])

[[90, 18, 21, 11], [50, 60, 70, 80], [10, 20, 30, 40]]
[10, 20, 30, 40]


In [31]:
#using array
print(arr2[::-1])
print()
print(arr2[::,::-1])
print()
print(arr2[::-1,2])
print()
print(arr2[::-1,::-1])
print()
print(arr2[::-1][2])
print()
print(arr2[::2,::2])
print()
print(arr2[:1:,::2])


[[90 18 21 11]
 [50 60 70 80]
 [10 20 30 40]]

[[40 30 20 10]
 [80 70 60 50]
 [11 21 18 90]]

[21 70 30]

[[11 21 18 90]
 [80 70 60 50]
 [40 30 20 10]]

[10 20 30 40]

[[10 30]
 [90 21]]

[[10 30]]


In [34]:
lst3=[[[10,20],[30,40]],[[1,2],[50,60]]]
arr3=np.array(lst3)
arr3

array([[[10, 20],
        [30, 40]],

       [[ 1,  2],
        [50, 60]]])

In [39]:
print(arr3[1,0,1])
print()
print(arr3[::,::,::])
print()
print(arr3[::-1,:1:,::2])

2

[[[10 20]
  [30 40]]

 [[ 1  2]
  [50 60]]]

[[[ 1]]

 [[10]]]
