#### operators in numpy

In [1]:
import numpy as np

In [2]:
l1=[1,2,3]
arr1=np.array(l1)
arr1

array([1, 2, 3])

In [3]:
l2=[6,7,8]
arr2=np.array(l2)
arr2

array([6, 7, 8])

##### Arithematic Operations-->(+, -, *, **, %, /, //)

In [4]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1**arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1%arr2)

[ 7  9 11]
[-5 -5 -5]
[ 6 14 24]
[   1  128 6561]
[0.16666667 0.28571429 0.375     ]
[0 0 0]
[1 2 3]


##### Comparision/Relational operators-->(==, !=, <, >, <=, >=)

In [5]:
print(arr1==arr2)
print(arr1!=arr2)
print(arr1<arr2)
print(arr1>arr2)
print(arr1<=arr2)
print(arr1>=arr2)

[False False False]
[ True  True  True]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]


- `all()`: returns True when all conditions are True
- `any()`: returns True if any one condition is True

In [6]:
print((arr1>5).all() and (arr1<10).all())
print((arr2>5).all() and (arr2<10).all())

False
True


In [7]:
print((arr1>5).any() and (arr1<10).any())
print((arr2>5).any() and (arr2<10).any())

False
True
