`Broadcasting`-->applying one value for each and every element. 

Rules
- elements must be equal(same size)-->ele==ele
- elements should be equal to 1 or empty--> ele==1 and ele==empty

In [1]:
import numpy as np

In [2]:
l1=[10,20,30]
arr1=np.array(l1)
print(arr1)
print(arr1.shape)
c=100

[10 20 30]
(3,)


In [3]:
arr1 + c

array([110, 120, 130])

In [4]:
l2=[11,12,13]
arr2=np.array(l2)
print(arr2)
print(arr2.shape)

[11 12 13]
(3,)


In [5]:
arr1+arr2

array([21, 32, 43])

In [6]:
arr3=np.array([100,200,300,400])
print(arr3)

[100 200 300 400]


In [7]:
'''
arr1+arr3
ValueError: operands could not be broadcast together with shapes (3,) (4,) 
'''

'\narr1+arr3\nValueError: operands could not be broadcast together with shapes (3,) (4,) \n'

In [8]:
arr4=np.array([[1,2,3],[5,6,7]])
print(arr4)
print(arr4.shape)

[[1 2 3]
 [5 6 7]]
(2, 3)


In [9]:
arr1+arr4

array([[11, 22, 33],
       [15, 26, 37]])

In [12]:
arr5=np.array([[[8],[5]],[[2],[1]],[[23],[36]]])
print(arr5)
print(arr5.shape)

[[[ 8]
  [ 5]]

 [[ 2]
  [ 1]]

 [[23]
  [36]]]
(3, 2, 1)


In [13]:
arr4+arr5

array([[[ 9, 10, 11],
        [10, 11, 12]],

       [[ 3,  4,  5],
        [ 6,  7,  8]],

       [[24, 25, 26],
        [41, 42, 43]]])