In [1]:
import numpy as np

In [3]:
arr1=np.arange(10,96,5)
print(arr1)
print(arr1.shape)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)


`reshape() `
- used to convert the one shape of arary to another shape of array
- to change the shape of array we have to give shape=(mutiples of shape of array)-->eg=18(multiples of 18)
- (-1)--> converts any shape of the array to 1D array

In [5]:
print(np.reshape(arr1,shape=(2,9)))
print()
print(np.reshape(arr1,shape=(3,6)))

[[10 15 20 25 30 35 40 45 50]
 [55 60 65 70 75 80 85 90 95]]

[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]


In [ ]:
arr2=np.reshape(arr1,(3,2,3))
print(arr2)
print(np.reshape(arr2,(-1))) 

[[[10 15 20]
  [25 30 35]]

 [[40 45 50]
  [55 60 65]]

 [[70 75 80]
  [85 90 95]]]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [11]:
arr3=np.array([[10,20,30,40,50,78],[2,4,5,60,64,28],[11,9,37,92,55,68]])
print(arr3)
print(arr3.shape)
print(arr3.ndim,arr3.size,sep='\n')
print()


[[10 20 30 40 50 78]
 [ 2  4  5 60 64 28]
 [11  9 37 92 55 68]]
(3, 6)
2
18



In [13]:
print(np.reshape(arr3,(3,2,1,3)))
print()
print(np.reshape(arr3,(3,3,2)))

[[[[10 20 30]]

  [[40 50 78]]]


 [[[ 2  4  5]]

  [[60 64 28]]]


 [[[11  9 37]]

  [[92 55 68]]]]

[[[10 20]
  [30 40]
  [50 78]]

 [[ 2  4]
  [ 5 60]
  [64 28]]

 [[11  9]
  [37 92]
  [55 68]]]
