``AGGREGATE/STATISTICAL METHODS``

In [1]:
import numpy as np

In [2]:
arr1=np.array([10,20,30])
print(arr1)

[10 20 30]


`power()`:used to square all the elements present in the array 

In [3]:
print(np.power(arr1,2))

[100 400 900]


`sum()`

In [4]:
print(np.sum(arr1))

60


`standard deviation`

In [5]:
print(np.std(arr1))

8.16496580927726


`mean()`

In [6]:
print(np.mean(arr1))

20.0


`variance()`:used to check how far the value is from mean value

In [7]:
print(np.var(arr1))

66.66666666666667


In [8]:
arr2=np.array([1,0,2])
print(arr2)

[1 0 2]


`exp()`:e=2.734

In [9]:
print(np.exp(arr2))

[2.71828183 1.         7.3890561 ]


`log()`:gives the value of particular power

In [10]:
arr3=np.array([2.71828183 ,1.         ,7.3890561 ])
print(arr3)
print(np.log(arr3))

[2.71828183 1.         7.3890561 ]
[1. 0. 2.]


In [11]:
arr4=np.array([10,2,15,5,9,20])
print(arr4)

[10  2 15  5  9 20]


`isin()`: works same as membership operator(in)

In [12]:
print(np.isin(20,arr4))
print()
print(np.isin([2,15,8,20],arr4))

True

[ True  True False  True]


`sort()`

In [13]:
print(np.sort(arr4))

[ 2  5  9 10 15 20]


`median()`:gives mid value

In [14]:
print(np.median(arr4))

9.5


`percentile()`

In [15]:
print(np.percentile(arr4,25))
print(np.percentile(arr4,50))
print(np.percentile(arr4,75))
print(np.percentile(arr4,100))

6.0
9.5
13.75
20.0


`where()`


In [16]:
print(arr4[np.where(arr4<11)])

[10  2  5  9]
