In [1]:
import numpy as np

In [2]:
arr1=np.array([10,20,30])
print(arr1)

[10 20 30]


In [ ]:
#copy-->independent- it doesn't depend
s_a=np.copy(arr1)
print(s_a)

s_a[0]=100
print(s_a)

[10 20 30]
[100  20  30]


In [6]:
#view-->dependent- becaues it uses same memory
arr3=arr1.view()
print('arr3:',arr3)
print('arr1:',arr1)

arr3[-1]=200
print('arr3:',arr3)
print('arr1:',arr1)

arr3: [10 20 30]
arr1: [10 20 30]
arr3: [ 10  20 200]
arr1: [ 10  20 200]
