In [11]:
import numpy as np

In [12]:
arr1=np.array([[1,2,3],[10,20,30]])
print(arr1)

[[ 1  2  3]
 [10 20 30]]


In [13]:
print(np.reshape(arr1,(-1)))

[ 1  2  3 10 20 30]


`ravel()`
- converts any shape of the array into 1D array(returns a view)
- if any changes made in new array ,it also changes in original array

In [14]:
x=arr1.ravel()
print(x)
print()
x[0]=50
print(arr1,x,sep='\n')

[ 1  2  3 10 20 30]

[[50  2  3]
 [10 20 30]]
[50  2  3 10 20 30]


In [15]:
arr2=np.array([[11,22,33],[4,67,80]])
print(arr2)

[[11 22 33]
 [ 4 67 80]]


`flatten()`
- Flattens a multi-dimensional array to a 1D array (returns a copy). 

In [16]:
y=arr2.flatten()
print(y)
print()
y[-1]=900
print(arr2,y,sep='\n')

[11 22 33  4 67 80]

[[11 22 33]
 [ 4 67 80]]
[ 11  22  33   4  67 900]
